### ISSUE TITLE
Feature Request: Allow Simple Image Optimizations Through the SDK

### ISSUE THREAD

**Issue by polluterofminds** [PinataCloud/pinata#13]
Pinata [already supports image optimizations](https://docs.pinata.cloud/gateways/image-optimizations). Since the SDK supports fetching files, it's be interesting to support optimizing those files if they are images. It could look something like: 

```
await pinata.gateways.get("Qm..").resize({width: 100, height: 100})
```

**Comment by stevedylandev** [comment]
Feature merged! Will be included in next release 🤝🏻
