### ISSUE TITLE
How can I track upload progress if uploading large file?

### ISSUE THREAD

**Issue by lazydevpro** [PinataCloud/pinata#4]
I have been trying to upload more than 1000 files at once and want to keep track of progress so far but I don't see any option to do so in documentation. How can I do it?

**Comment by stevedylandev** [comment]
Hey there! That might be something you might need to do using the [API directly](https://docs.pinata.cloud/api-reference/endpoint/pin-file-to-ipfs) with a fetch library like Got. Another option would be trying out our [Pinata Go CLI](https://github.com/PinataCloud/pinata-go-cli)!
