### ISSUE TITLE
I am getting a NetworkError

### ISSUE THREAD

**Issue by Boby900** [PinataCloud/pinata#41]
while creating a group, I am getting a Network Error.
If I am calling this 
```tsx
 const group = await pinata.groups.create({
        name: "My Album",
        isPublic: true
      });
```
with the same name again it's giving me this error and If I change the name to something else then a new group is created.

_If it could be more descriptive like this group already existed then that would be better_

![Screenshot (651)](https://github.com/user-attachments/assets/ff3e1dfa-0bb9-48d8-8379-fe64f629e8e3)

**Comment by stevedylandev** [comment]
Hey @Boby900! You're totally right. We have a ticket out to make this more clear so I'll leave this issue up until the API is patched :)

**Comment by stevedylandev** [comment]
Hey @Boby900! We now have a proper error when trying to upload a file to an existing group. Let us know if you have any issues! :)
