### ISSUE TITLE
Provide pinata PeerIDs for folks to connect to

### ISSUE THREAD

**Issue by glitch003** [PinataCloud/pinata#45]
Hi, this issue was closed as completed https://github.com/PinataCloud/Pinata-SDK/issues/5 in the old SDK, but I don't see the data anywhere.  Could you provide the full addresses for pinata nodes?  I can see the multiaddr via cid.contact but don't know the ports or if it's TCP/UDP etc.  Having full multiaddr with peer id documented would be very helpful for users that are integrating existing IPFS services with Pinata, like us, at Lit Protocol.

![Screenshot 2024-10-21 at 5 37 27 PM](https://github.com/user-attachments/assets/61f10cf5-5b3a-4a42-90e2-9547038f62ea)

**Comment by stevedylandev** [comment]
Hey there! We actually have setup the DNS as a more stable way to provide external connections since our infra shifts from time to time. You can still connect to it by using the following commands:

```
ipfs swarm connect /dnsaddr/bitswap.pinata.cloud
```

```
ipfs config --json Peering.Peers '[{ "ID": "Qma8ddFEQWEU8ijWvdxXm3nxU7oHsRtCykAaVz8WUYhiKn", "Addrs": ["/dnsaddr/bitswap.pinata.cloud"] }]'
```

Thank you for bringing this up though! We will add the information to our docs :)

**Comment by stevedylandev** [comment]
Added to the docs! Will mark this as complete but please let us know if you have any other questions!
